### ISSUE TITLE
Autocomplete (aka prefix search) with doublearray

### ISSUE THREAD

**Issue by thangngoc89** [takuyaa/doublearray#3]
First, I want to thank you for writing and making this repo available on github. I have search in many papers and implementations but I can't find any of them mentioning using double-array as a autocomplete data structure. So I wonder if that is even possible at all ?

**Comment by takuyaa** [comment]
@thangngoc89 
Maybe, it's original paper is [[Aoe 1989]](https://ieeexplore.ieee.org/document/31365/).
Double-Array trie is used in part of Japanese morphological analyzer [MeCab](https://github.com/taku910/mecab), that is one of most famous NLP tool in Japan. MeCab uses [Darts](http://chasen.org/~taku/software/darts/) as a library that implements Double-Array data structure, internally.
See also: [An Implementation of Double-Array Trie](https://linux.thai.net/~thep/datrie/).

**Comment by takuyaa** [comment]
This issue is not directly related to this library. Close #3 .
